import Adresse
import Agent
import Asterix
import ChefCompagne
import Client
import Compagne
#import Contact
import Email
import Equipe
import Etat
import Meeting
import Operateur
#import Prospect
import Qualification
import Service
import Superviseur
import Trace
import Type
import EPAC
#import Appel